version: '3.3'

services:
  postgres:
    image: "postgres:13.3"
    container_name: "otus-postgres"
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5430:5432"